### ISSUE TITLE
Docker issue when building the autonomous exploration package from github

### ISSUE THREAD

**Issue by Fabulani** [Fabulani/xplorer#3]
- Branch: fabiano
- Repeating the issue: `docker-compose up`
- Expected behavior: docker compose should build and launch 2 containers: one for rosbridge, and another one for the autonomous exploration alg (`explore` service). The `explore` container should then execute the launch file command and the auto-exp should run in the background (?). The files for the package are cloned from the git repo and then built using `colon`.
- Issue: the `explore` container quits with an error:
```sh
explore      | Package 'explore_lite' not found: "package 'explore_lite' not found, searching: ['/opt/ros/galactic']"
explore exited with code 1
```
Which is strange, since in the Dockerfile, there's the following instructions:
```dockerfile
# Copy and build ROS2 packages inside the workspace
RUN mkdir /xplorer_ws/src -p && \
    cd /xplorer_ws/src && \
    git clone https://github.com/robo-friends/m-explore-ros2.git main && \
    . /opt/ros/$ROS_DISTRO/setup.sh && \
    rosdep install --from-paths . --ignore-src -r -y && \
    colcon build
```
The service is described like so in `docker-compose.yml`:
```yml
  explore:
    container_name: explore
    build: .
    command: ros2 launch explore_lite explore.launch.py
    env_file:
      - environment.env
    volumes:
      - myros2volume:/workspaces
```
